In [1]:
import os
os.chdir("../")
%pwd

'd:\\AI\\NLP\\HandsOn\\Text Summarization'

In [2]:
import pandas as pd
df = pd.read_csv(r'artifacts\data_ingestion\ted_main.csv')
df.head(5)

,comments,description,duration,event,film_date,languages,main_speaker,name,num_speaker,published_date,ratings,related_talks,speaker_occupation,tags,title,url,views
0,4553,Sir Ken Robinson makes an entertaining and pro...,1164,TED2006,1140825600,60,Ken Robinson,Ken Robinson: Do schools kill creativity?,1,1151367060,"[{'id': 7, 'name': 'Funny', 'count': 19645}, {...","[{'id': 865, 'hero': 'https://pe.tedcdn.com/im...",Author/educator,"['children', 'creativity', 'culture', 'dance',...",Do schools kill creativity?,https://www.ted.com/talks/ken_robinson_says_sc...,47227110
1,265,With the same humor and humanity he exuded in ...,977,TED2006,1140825600,43,Al Gore,Al Gore: Averting the climate crisis,1,1151367060,"[{'id': 7, 'name': 'Funny', 'count': 544}, {'i...","[{'id': 243, 'hero': 'https://pe.tedcdn.com/im...",Climate advocate,"['alternative energy', 'cars', 'climate change...",Averting the climate crisis,https://www.ted.com/talks/al_gore_on_averting_...,3200520
2,124,New York Times columnist David Pogue takes aim...,1286,TED2006,1140739200,26,David Pogue,David Pogue: Simplicity sells,1,1151367060,"[{'id': 7, 'name': 'Funny', 'count': 964}, {'i...","[{'id': 1725, 'hero': 'https://pe.tedcdn.com/i...",Technology columnist,"['computers', 'entertainment', 'interface desi...",Simplicity sells,https://www.ted.com/talks/david_pogue_says_sim...,1636292
3,200,"In an emotionally charged talk, MacArthur-winn...",1116,TED2006,1140912000,35,Majora Carter,Majora Carter: Greening the ghetto,1,1151367060,"[{'id': 3, 'name': 'Courageous', 'count': 760}...","[{'id': 1041, 'hero': 'https://pe.tedcdn.com/i...",Activist for environmental justice,"['MacArthur grant', 'activism', 'business', 'c...",Greening the ghetto,https://www.ted.com/talks/majora_carter_s_tale...,1697550
4,593,You've never seen data presented like this. Wi...,1190,TED2006,1140566400,48,Hans Rosling,Hans Rosling: The best stats you've ever seen,1,1151440680,"[{'id': 9, 'name': 'Ingenious', 'count': 3202}...","[{'id': 2056, 'hero': 'https://pe.tedcdn.com/i...",Global health expert; data visionary,"['Africa', 'Asia', 'Google', 'demo', 'economic...",The best stats you've ever seen,https://www.ted.com/talks/hans_rosling_shows_t...,12005869

In [3]:
df.columns

Index(['comments', 'description', 'duration', 'event', 'film_date',
       'languages', 'main_speaker', 'name', 'num_speaker', 'published_date',
       'ratings', 'related_talks', 'speaker_occupation', 'tags', 'title',
       'url', 'views'],
      dtype='object')

In [4]:
relevant_fields = ['description','tags', 'title', 'ratings','url']
ir_relevant_fields = [field for field in df.columns if field not in relevant_fields]
df = df.drop(ir_relevant_fields, axis=1, inplace=False)

In [5]:
df.head(5)

,description,ratings,tags,title,url
0,Sir Ken Robinson makes an entertaining and pro...,"[{'id': 7, 'name': 'Funny', 'count': 19645}, {...","['children', 'creativity', 'culture', 'dance',...",Do schools kill creativity?,https://www.ted.com/talks/ken_robinson_says_sc...
1,With the same humor and humanity he exuded in ...,"[{'id': 7, 'name': 'Funny', 'count': 544}, {'i...","['alternative energy', 'cars', 'climate change...",Averting the climate crisis,https://www.ted.com/talks/al_gore_on_averting_...
2,New York Times columnist David Pogue takes aim...,"[{'id': 7, 'name': 'Funny', 'count': 964}, {'i...","['computers', 'entertainment', 'interface desi...",Simplicity sells,https://www.ted.com/talks/david_pogue_says_sim...
3,"In an emotionally charged talk, MacArthur-winn...","[{'id': 3, 'name': 'Courageous', 'count': 760}...","['MacArthur grant', 'activism', 'business', 'c...",Greening the ghetto,https://www.ted.com/talks/majora_carter_s_tale...
4,You've never seen data presented like this. Wi...,"[{'id': 9, 'name': 'Ingenious', 'count': 3202}...","['Africa', 'Asia', 'Google', 'demo', 'economic...",The best stats you've ever seen,https://www.ted.com/talks/hans_rosling_shows_t...

In [6]:
df['title'][0]

'Do schools kill creativity?'

In [7]:
df['description'][0]

'Sir Ken Robinson makes an entertaining and profoundly moving case for creating an education system that nurtures (rather than undermines) creativity.'

In [8]:
df['ratings'][0]

"[{'id': 7, 'name': 'Funny', 'count': 19645}, {'id': 1, 'name': 'Beautiful', 'count': 4573}, {'id': 9, 'name': 'Ingenious', 'count': 6073}, {'id': 3, 'name': 'Courageous', 'count': 3253}, {'id': 11, 'name': 'Longwinded', 'count': 387}, {'id': 2, 'name': 'Confusing', 'count': 242}, {'id': 8, 'name': 'Informative', 'count': 7346}, {'id': 22, 'name': 'Fascinating', 'count': 10581}, {'id': 21, 'name': 'Unconvincing', 'count': 300}, {'id': 24, 'name': 'Persuasive', 'count': 10704}, {'id': 23, 'name': 'Jaw-dropping', 'count': 4439}, {'id': 25, 'name': 'OK', 'count': 1174}, {'id': 26, 'name': 'Obnoxious', 'count': 209}, {'id': 10, 'name': 'Inspiring', 'count': 24924}]"

In [9]:
df['tags'][0]

"['children', 'creativity', 'culture', 'dance', 'education', 'parenting', 'teaching']"

In [10]:
df1 = pd.read_csv(r"artifacts\data_ingestion\transcripts.csv")
df1.head(5)

,transcript,url
0,Good morning. How are you?(Laughter)It's been ...,https://www.ted.com/talks/ken_robinson_says_sc...
1,"Thank you so much, Chris. And it's truly a gre...",https://www.ted.com/talks/al_gore_on_averting_...
2,"(Music: ""The Sound of Silence,"" Simon & Garfun...",https://www.ted.com/talks/david_pogue_says_sim...
3,If you're here today — and I'm very happy that...,https://www.ted.com/talks/majora_carter_s_tale...
4,"About 10 years ago, I took on the task to teac...",https://www.ted.com/talks/hans_rosling_shows_t...

In [11]:
merged_df = df.merge(df1, on='url').drop('url', axis=1)
merged_df

,description,ratings,tags,title,transcript
0,Sir Ken Robinson makes an entertaining and pro...,"[{'id': 7, 'name': 'Funny', 'count': 19645}, {...","['children', 'creativity', 'culture', 'dance',...",Do schools kill creativity?,Good morning. How are you?(Laughter)It's been ...
1,With the same humor and humanity he exuded in ...,"[{'id': 7, 'name': 'Funny', 'count': 544}, {'i...","['alternative energy', 'cars', 'climate change...",Averting the climate crisis,"Thank you so much, Chris. And it's truly a gre..."
2,New York Times columnist David Pogue takes aim...,"[{'id': 7, 'name': 'Funny', 'count': 964}, {'i...","['computers', 'entertainment', 'interface desi...",Simplicity sells,"(Music: ""The Sound of Silence,"" Simon & Garfun..."
3,"In an emotionally charged talk, MacArthur-winn...","[{'id': 3, 'name': 'Courageous', 'count': 760}...","['MacArthur grant', 'activism', 'business', 'c...",Greening the ghetto,If you're here today — and I'm very happy that...
4,You've never seen data presented like this. Wi...,"[{'id': 9, 'name': 'Ingenious', 'count': 3202}...","['Africa', 'Asia', 'Google', 'demo', 'economic...",The best stats you've ever seen,"About 10 years ago, I took on the task to teac..."
...,...,...,...,...,...
2462,"Between 2008 and 2016, the United States depor...","[{'id': 3, 'name': 'Courageous', 'count': 24},...","['TED Residency', 'United States', 'community'...",What we're missing in the debate about immigra...,"So, Ma was trying to explain something to me a..."
2463,How can you study Mars without a spaceship? He...,"[{'id': 22, 'name': 'Fascinating', 'count': 32...","['Mars', 'South America', 'TED Fellows', 'astr...",The most Martian place on Earth,This is a picture of a sunset on Mars taken by...
2464,Science fiction visions of the future show us ...,"[{'id': 1, 'name': 'Beautiful', 'count': 14}, ...","['AI', 'ants', 'fish', 'future', 'innovation',...",What intelligent machines can learn from a sch...,"In my early days as a graduate student, I went..."
2465,In an unmissable talk about race and politics ...,"[{'id': 11, 'name': 'Longwinded', 'count': 3},...","['Internet', 'TEDx', 'United States', 'communi...",A black man goes undercover in the alt-right,I took a cell phone and accidentally made myse...
2466,With more than half of the world population li...,"[{'id': 21, 'name': 'Unconvincing', 'count': 2...","['cities', 'design', 'future', 'infrastructure...",How a video game might help us build better ci...,"We humans are becoming an urban species, so ci..."

------------

### Data Standerization

In [ ]:
import nltk
import re
from pathlib import Path
from typing import List, Optional, Set
import string
import os
from TextSummarizer.logging import logger

def setup_nltk_environment(data_dir: Optional[str] = None) -> str:
    if data_dir:
        nltk_data_dir = Path(data_dir)
        nltk_data_dir.mkdir(parents=True, exist_ok=True)
        
        # Set NLTK_DATA environment variable
        os.environ['NLTK_DATA'] = str(nltk_data_dir)
        
        # Clear existing paths and add custom path
        nltk.data.path = [str(nltk_data_dir)]
        return str(nltk_data_dir)
    return nltk.data.find('.').parent

def download_nltk_models(data_dir: Optional[str] = None, 
                        models: Optional[List[str]] = None) -> Set[str]:
    default_models = [
        'punkt',           # Sentence tokenizer
        'stopwords',       # Common stopwords
        'averaged_perceptron_tagger',  # POS tagger
        'wordnet',         # Lexical database
        'words'            # Word lists
    ]
    
    # Setup environment if custom directory provided
    if data_dir:
        setup_nltk_environment(data_dir)
    
    models_to_download = models if models else default_models
    downloaded_models = set()
    
    for model in models_to_download:
        try:
            nltk.download(model, 
                         download_dir=data_dir if data_dir else None,
                         quiet=True)
            downloaded_models.add(model)
            logger.info(f"Successfully downloaded '{model}' to {data_dir if data_dir else 'default location'}")
        except Exception as e:
            logger.info(f"Failed to download '{model}': {e}")
    
    return downloaded_models

In [ ]:
def clean_text(text: str) -> str:
    # Convert to lowercase
    text = text.lower()
    
    # Remove special characters and digits
    text = re.sub(r'[^a-zA-Z\s]', '', text)
    
    # Remove extra whitespace
    text = ' '.join(text.split())
    
    return text

def remove_stopwords(text: str, custom_stopwords: Optional[Set[str]] = None) -> str:
    try:
        from nltk.corpus import stopwords
        stop_words = set(stopwords.words('english'))
        if custom_stopwords:
            stop_words.update(custom_stopwords)
    except LookupError:
        print("Downloading stopwords...")
        nltk.download('stopwords')
        from nltk.corpus import stopwords
        stop_words = set(stopwords.words('english'))
    
    words = text.split()
    filtered_words = [word for word in words if word not in stop_words]
    return ' '.join(filtered_words)

def lemmatize_text(text: str) -> str:
    try:
        from nltk.stem import WordNetLemmatizer
        lemmatizer = WordNetLemmatizer()
    except LookupError:
        print("Downloading required models...")
        nltk.download('wordnet')
        from nltk.stem import WordNetLemmatizer
        lemmatizer = WordNetLemmatizer()
    
    words = text.split()
    lemmatized_words = [lemmatizer.lemmatize(word) for word in words]
    return ' '.join(lemmatized_words)

def standardize_text(text: str, 
                    remove_stops: bool = True,
                    lemmatize: bool = True,
                    custom_stopwords: Optional[Set[str]] = None) -> str:
    # Clean the text first
    text = clean_text(text)
    
    # Remove stopwords if requested
    if remove_stops:
        text = remove_stopwords(text, custom_stopwords)
    
    # Lemmatize if requested
    if lemmatize:
        text = lemmatize_text(text)
    
    return text

NLTK data directory: D:\AI\NLP\HandsOn\Text Summarization\artifacts\models
Successfully downloaded 'punkt' to D:\AI\NLP\HandsOn\Text Summarization\artifacts\models
Successfully downloaded 'stopwords' to D:\AI\NLP\HandsOn\Text Summarization\artifacts\models
Successfully downloaded 'averaged_perceptron_tagger' to D:\AI\NLP\HandsOn\Text Summarization\artifacts\models
Successfully downloaded 'wordnet' to D:\AI\NLP\HandsOn\Text Summarization\artifacts\models
Successfully downloaded 'words' to D:\AI\NLP\HandsOn\Text Summarization\artifacts\models
Downloaded models: {'punkt', 'stopwords', 'words', 'wordnet', 'averaged_perceptron_tagger'}

Original text: The quick brown fox's jump wasn't particularly high! However, it was jumping over lazy dogs.

Cleaned text: the quick brown foxs jump wasnt particularly high however it was jumping over lazy dogs

Text without stopwords: quick brown foxs jump wasnt particularly high however jumping lazy dogs

Lemmatized text: the quick brown fox jump wasnt particularly high however it wa jumping over lazy dog

Fully standardized text: quick brown fox jump wasnt particularly high however jumping lazy dog

Standardized text with custom stopwords: fox jump wasnt particularly high however jumping lazy dog

In [ ]:
# Specify custom directory
custom_dir = r"D:\AI\NLP\HandsOn\Text Summarization\artifacts\models"

# Setup NLTK environment with custom directory
nltk_dir = setup_nltk_environment(custom_dir)
print(f"NLTK data directory: {nltk_dir}")

# Download required models to custom directory
downloaded = download_nltk_models(data_dir=custom_dir)
print(f"Downloaded models: {downloaded}")

# Example text
sample_text = "The quick brown fox's jump wasn't particularly high! However, it was jumping over lazy dogs."

# Test the functions
print("\nOriginal text:", sample_text)
print("\nCleaned text:", clean_text(sample_text))
print("\nText without stopwords:", remove_stopwords(clean_text(sample_text)))
print("\nLemmatized text:", lemmatize_text(clean_text(sample_text)))
print("\nFully standardized text:", standardize_text(sample_text))